spring:
  application:
    name:  trend-trading-backtest-view
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411